from django.db import models
import datetime
import lorem #used to seed db with autogenerated content
from random import randint as ri

def rand(lst):
    return lst[ri(0, len(lst)-1)]

ALPHANUM = 'abcdefghijklmnopqrstuvwxyz0123456789'
name = ''

class Post(models.Model):
    author = models.CharField(max_length=25, default="Anonymous")
    title = models.CharField(max_length=144, default="Post Name")
    time = models.DateTimeField(auto_now_add=True, blank=True)
    content = models.CharField(max_length=10000, default="Post Content")
    comments = []

class User(models.Model):
    username = models.CharField(max_length=25, default="Anonymous")
    posts = []

class Comment(models.Model):
    author = None
    content = models.CharField(max_length=10000, default="Comment")
    parent = None 
    comments = []


users = User.objects.all()
the_set = set([user.username for user in users])
posts = Post.objects.all()
first_25 = Post.objects.all()[:25]
first_10 = Post.objects.all()[:10]
user_list = []


for name in set([post.author for post in posts]):
    _u = User.objects.create(username=name)
    user_list.append(_u)
    _u.save()

for user in user_list:
    user.posts = [post for post in posts if post.author == user.username]
    user.save() 

for post in user.posts:
    post.comments = [Comment(lorem.sentence()) for i in range(5)]



for user in user_list:
    for post in user.posts:
        c = Comment(content=lorem.sentence())
        c.comments.append(Comment(content=lorem.sentence()))
        c.comments[-1].parent = c
        c.parent = post
        post.comments.append(c)

# for user in user_list:
#     for post in user.posts:
#         for comment in post.comments:
#             comment.content = lorem.sentence()
#             comment.save()


# z = zip(first_25, [post.comments for post in first_25])
# d = dict(z)
# dict_items = list(d.items())
'''
 Anonymous 07/25/22(Mon)23:29:41 No.606992621   [Reply]▶>>607010219
The first thing I will do when I get this will put my hand in the Goblet of Fire.
+63 replies and 10 images omitted. Click here to view.
'''
