from django.urls import path
from . import views
from random import randint as ri

urlpatterns = [path('', views.index, name='index'),
# path('user/', views.user2, name="user"),
path('page/1', views.user1, name="user1"),
path('page/2', views.user2, name="user2"),
path('page/3', views.user3, name="user3"),
path('page/4', views.user4, name="user4"),
path('page/5', views.user5, name="user5"),
path('page/6', views.user6, name="user6"),
path('page/7', views.user7, name="user7"),
path('page/8', views.user8, name="user8"),
path('page/9', views.user9, name="user9"),
path('page/10', views.user10, name="user10"),
path('tree/', views.tree, name="tree"),
path('1/', views.one, name="one"),
path('2/', views.two, name="two"),
path('3/', views.three, name="three"),
path('4/', views.four, name="four"),
path('5/', views.five, name="five"),
path('6/', views.six, name="six"),
path('7/', views.seven, name="seven"),
path('8/', views.eight, name="eight"),
path('9/', views.nine, name="nine"),
path('10/', views.ten, name="ten"),
path('11/', views.eleven, name="ten"),
path('12/', views.twelve, name="ten"),
path('13/', views.thirteen, name="ten"),
path('14/', views.fourteen, name="ten"),
path('15/', views.fifteen, name="ten"),
path('16/', views.sixteen, name="ten"),
path('17/', views.seventeen, name="ten"),
path('18/', views.eighteen, name="ten"),
path('19/', views.nineteen, name="ten"),
path('20/', views.twenty, name="ten"),
path('21/', views.twenty_one, name="ten"),
path('22/', views.twenty_two, name="ten"),
path('23/', views.twenty_three, name="ten"),
path('24/', views.twenty_four, name="ten"),
path('reddit/', views.reddit, name="reddit"),
]