from django.urls import path
from . import views
from random import randint as ri
from .models import user_list 
urlpatterns = [path('', views.index, name='index'),

# path('tree/', views.tree, name="tree"),
# path('user/', views.user, name="user"),
# path('1/', views.one, name="one"),
# path('/user/Numquam', views.user, name="user"),
# path('2/', views.two, name="two"),
# path('3/', views.three, name="three"),
# path('4/', views.four, name="four"),
# path('5/', views.five, name="five"),
# path('6/', views.six, name="six"),
# path('7/', views.seven, name="seven"),
# path('8/', views.eight, name="eight"),
# path('9/', views.nine, name="nine"),
# path('10/', views.ten, name="ten"),
# path('11/', views.eleven, name="ten"),
# path('12/', views.twelve, name="ten"),
# path('13/', views.thirteen, name="ten"),
# path('14/', views.fourteen, name="ten"),
# path('15/', views.fifteen, name="ten"),
# path('16/', views.sixteen, name="ten"),
# path('17/', views.seventeen, name="ten"),
# path('18/', views.eighteen, name="ten"),
# path('19/', views.nineteen, name="ten"),
# path('20/', views.twenty, name="ten"),
# path('21/', views.twenty_one, name="ten"),
# path('22/', views.twenty_two, name="ten"),
# path('23/', views.twenty_three, name="ten"),
# path('24/', views.twenty_four, name="ten"),
path('1/', views.page1, name="page1"),
path('2/', views.page2, name="page2"),
path('3/', views.page3, name="page3"),
path('4/', views.page4, name="page4"),
path('5/', views.page5, name="page5"),
path('6/', views.page6, name="page6"),
path('7/', views.page7, name="page7"),
path('8/', views.page8, name="page8"),
path('9/', views.page9, name="page9"),
path('10/', views.page10, name="page10"),

] + [path(f'boards/user/{user.username}/', views.user, name=f"{user.username}") for user in user_list]