# Generated by Django 4.0.6 on 2022-07-19 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 5, 4, 54, 705019, tzinfo=utc)),
        ),
    ]
