# Generated by Django 4.0.6 on 2022-07-19 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_post_image_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 13, 18, 7, 333450, tzinfo=utc)),
        ),
    ]
