# Generated by Django 4.0.6 on 2022-07-20 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_product_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 17, 44, 47, 225681, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='description goes here'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(verbose_name='price goes here'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default='summary goes here'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(default='title goes here'),
        ),
    ]
