# Generated by Django 4.0.6 on 2022-07-22 21:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_post_time_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 21, 2, 35, 632758, tzinfo=utc)),
        ),
    ]
