# Generated by Django 4.0.6 on 2022-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Post Name', max_length=144)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(default='Post Content', max_length=10000)),
            ],
        ),
    ]
