# Generated by Django 4.0.6 on 2022-07-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0002_adj_adv_art_prep_v'),
    ]

    operations = [
        migrations.CreateModel(
            name='W',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=5)),
            ],
        ),
    ]
