# Generated by Django 4.0.6 on 2022-07-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_rename_name_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default='Comment', max_length=10000),
        ),
    ]
